### PR TITLE
Python 3.6 invalid escape sequence deprecation fixes

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@tartley ping? is there any chance to get this into a release?

**Comment by RonnyPfannschmidt** [comment]
@tartley ping? is there any chance to get this into a release? pytest users keep running into it

**Comment by anthrotype** [comment]
> is there any chance to get this into a release?

yes, please!

**Comment by RonnyPfannschmidt** [comment]
@wiggin15 thanks for the merge, is there anything we can do to help the inception of a new release

**Comment by wiggin15** [comment]
I released a new version.
PyPI wouldn't let me upload both "tar.gz" and "zip" source distributions (it says `Upload failed (400): Duplicate file upload detected.` even though the files are different. I think one of many bugs on PyPI) so I only uploaded the tar.gz type and the wheel.

**Comment by RonnyPfannschmidt** [comment]
Awesome, thanks :)

**Pull request merged**
