### PR TITLE
Add some styles

### PR DESCRIPTION
**Pull request by SeaHOH**
1. UNDERLINE/UNDERLINE_OFF
1. OVERLINE/OVERLINE_OFF
1. REVERSE/INVERSE_OFF
1. CONCEAL/REVEAL

Only tested on Win7.

### CODE REVIEW

**Comment by SeaHOH** [comment]
@wiggin15 Can you tell me what you think about this PR? Thanks.

**Comment by wiggin15** [comment]
These new styles don't work on Windows terminals (cmd/PowerShell) and some don't have wide support in Unix terminals either (e.g. `OVERLINE` doesn't work in iTerm). I tried your branch on Windows 7 and couldn't see them.
Since there is no Windows support we decided not to support these styles (see https://github.com/tartley/colorama/issues/38#issuecomment-128834060)

**Comment by SeaHOH** [comment]
Thanks for review.
How about `REVERSE/INVERSE_OFF` and `CONCEAL/REVEAL`? I think them works well.

**Comment by Evidlo** [comment]
@wiggin15 A later comment in #38 mentions that underline, reverse and conceal are supported in modern powershell.

**Comment by tartley** [comment]
Hey. FYI, Yesterday I created [a PR to test releases](https://github.com/tartley/colorama/pull/276) before we push them to PyPI. When that is merged, I'll be more confident about resuming merges and releases. I'll try to look at this PR soon. Thank you for creating it!

**Comment by JamesTheAwesomeDude** [comment]
I would appreciate support for the `'\x1b[8m'` "conceal" command, if that ever gets merged.

MATE terminal supports it \(haven't tested on other terminal emulators yet\), but on Windows CMD with Colorama 0.4.6, it doesn't work.

**Pull request closed without merging**
