### PR TITLE
Add initialization counter

### LINKED ISSUE #205: Handle multiple calls to init() and deinit() properly
Looking at this code: https://github.com/tartley/colorama/blob/master/colorama/initialise.py#L23

It looks like the code currently doesn't properly handle calling `init()` multiple times, I'd expect the `init()` function to set some internal state to know that it is already inited (maybe with a counter, in case nested `init()`/`deinit()` pairs should be supported?). Same with calling `deinit()`, it doesn't seem to always restore things properly.

Example code:

    import colorama
    colorama.init()
    colorama.init()
    colorama.deinit()

(of course, it might not be that obvious, but imagine two libraries want to initialize colorama in some situations)

Maybe it should also support nested `init()`/`deinit()` pairs:

    import colorama
    colorama.init()  # Initialized now
    colorama.init()  # Still initialized, maybe increase "refcount"/"initcount"
    colorama.deinit()  # Still initialized, because init was called twice
    colorama.deinit()  # Actually deinitialize, as the "refcount"/"initcount" will go to zero

Similar logic probably applies to `reinit()`, not sure.

### PR DESCRIPTION
**Pull request by Gaming32**
Resolves #205.

### CODE REVIEW

**Comment by tartley** [comment]
Hey. FYI, Yesterday I created [a PR to test releases](https://github.com/tartley/colorama/pull/276) before we push them to PyPI. When that is merged, I'll be more confident about resuming merges and releases. I'll try to look at this PR soon. Thank you for creating it!

The above is cut-and-paste to everyone. To you especially: thank you, that is a rubbish bug, and I'm really happy to see a fix for it!

**Comment by Erotemic** [comment]
Getting this fixed would help my use cases. Alternatively, if I had a way of knowing if colorama was ever initialized (even if it was deinitialized later), that would be enough for me. Currently I'm testing if `colorama.initialise.atexit_done` is Falsy, which works, but may not be the most stable test for this.

**Comment by Gaming32** [comment]
@tartley Any updates on this?

**Comment by tartley** [comment]
No updates currently, no.

But! For various reasons, I plan to give Colorama some love soon.

**Comment by tartley** [comment]
An alternative approach to these problems has been suggested. Instead of modifying the poorly thought out interface and behavior of the original 'init' function, which is nontrivial and might be relied upon by existing programs, a proposal has been made by njsmith to add a new function, in parallel with init, which behaves more sanely, and hopefully will address your issues with it.

See njsmith's final comment [here](https://github.com/tartley/colorama/pull/139) ("I would like to sneak one more feature in...") before I merged that PR. The intention is to merge that relatively trivial PR, then make a release.

**Pull request closed without merging**
