### PR TITLE
Replace pypip.in badge with shield.io

### PR DESCRIPTION
**Pull request by clenk**
pypip.in is down ( badges/pypipins#37 )

### CODE REVIEW

**Comment by tartley** [comment]
:+1: renders for me :-)

**Comment by clenk** [comment]
Do you mean the pypip.in one renders for you? Is it in your browser's cache?

I get a 404 from https://pypip.in/version/colorama/badge.svg

**Comment by tartley** [comment]
sorry, I meant the NEW shield.io one renders for me.

**Comment by wiggin15** [comment]
Hi @clenk. Thanks for the pull request. I see we have a broken link. Does the badge always show "v1.0.0"? Is there a way to make it automagically take the correct version from PyPI (the current version is 0.3.7). I don't know what the older badge showed.

**Comment by clenk** [comment]
Oops, it was pulling the version for the wrong package on PyPI. Should be correct now.

**Comment by wiggin15** [comment]
Thanks!

**Pull request merged**
