### PR TITLE
Adds link method for adding hyperlinks

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes: #134

### CODE REVIEW

**Comment by ssbarnea** [comment]
@egmontkob

**Comment by wiggin15** [comment]
Hi. Thanks for the PR. The problem I see with this is that there is no comparable feature (that I know of) on Windows terminals (e.g. "cmd"), and colorama is all about making the ANSI codes support both Windows and Unix platforms (more than convenience for creating and printing the codes). 
See also https://github.com/tartley/colorama/issues/38#issuecomment-128834060.

**Comment by skyem123** [comment]
It's probably possible to imitate this feature on Windows, but I think that'd be like reinventing curses (and I don't know if you can get mouse input while also having a scrollback)?

**Comment by ssbarnea** [comment]
@wiggin15 The fact that one specific terminal does no supports a feature is not a good enough reason for not implementing a feature at all. I am aware about at least 4 different terminals used on windows: old (bad) cmd, powershell, new bash terminal from linux subsystem (apparently different than cmd)  and putty. 

I stopped using Windows machines years ago so it may be quite hard to test especially due to their various versions. Also, it would not be hard to add some conditionals for disabling this functionality on win32 but I am afraid it is impossible to determine if current terminal supports it or not. We can only assume that is up to the colorama library user to decide when to use this feature or not.

So please let me know what else can be do to implement this feature in colorama?

**Comment by wiggin15** [comment]
This isn't about one specific terminal.
The purpose of colorama, as written in the README:

> Makes ANSI escape character sequences (for producing colored terminal text and cursor positioning) work under MS Windows.

We do this by converting ANSI codes to Win32 API calls when we see them written to stdout/stderr. We try to support as many ANSI codes as possible (not just colors), but only if they _can_ be converted to Windows API for Windows terminals (cmd and the others). When this is not possible, we don't add support for the codes.
This is true for other ANSI codes that we couldn't convert, like Underline, Blink (#38), Italic (#122), etc.
Unfortunately I don't think there is a Windows function to add a link to a Windows console.

I appreciate the effort and wanting to contribute, and I know it is frustrating that we can't add all available codes, but this is a decision we made long ago.

Check out [blessings](https://pypi.org/project/blessings) or other packages that are intended to provide convenience methods for printing ANSI codes, and should work with colorama.

**Pull request closed without merging**
