### PR TITLE
Prevent exponential number of calls while accessing "closed" / "isatty" (#196)

### PR DESCRIPTION
**Pull request by Delgan**
See #197 for extended discussion.

### CODE REVIEW

**Comment by bbayles** [comment]
This does fix the problem in #196.

**Comment by wiggin15** [comment]
@Delgan  I _think_ I understand [your comment](https://github.com/tartley/colorama/pull/197#issuecomment-429637613) in #197 about the call traces being more complex than needed, but I don't think I follow what the problem in #196 is exactly. If we wrap the streams too many times then this fix will only be a temporary relief and not a real fix, because there will still be too many nesting calls. Won't there..? If I understand correctly the problem was _not_ maximum recursion?

It will help to understand the problem if you can provide a minimal sample code (without modifying colorama) that reproduces this and explain exactly what happens. Thanks.

**Comment by wiggin15** [comment]
Thanks @Delgan . This is a fairly simple change and if it has this big an effect I will merge this. One question, though: if we revert the change in 2057f03 (make `closed` and `isatty` properties), will that make the potential `RecursionError` in this case go away?

**Comment by wiggin15** [comment]
Thanks!

**Pull request merged**
