### PR TITLE
Minor updates to formatting, phrasing

### PR DESCRIPTION
**Pull request by Zearin**
Small stuff, but good stuff

### CODE REVIEW

**Comment by tartley** [comment]
Brill, thanks! Personally I like all these changes except for the introduction of a couple of ellipsis characters - just because I worry that non-ASCII characters in a README might fail to render correctly in some contexts because there's no explicitly specified encoding. Am I being foolishly conservative? Plus, I'd like to add a "Thanks" line for Zearin (for anyone who contributes, obviously, apologies to anyone that has been accidentally missed)

**Comment by Zearin** [comment]
> On Apr 24, 2015, at 4:55 PM, Jonathan Hartley <notifications@github.com> wrote:
> 
> Brill, thanks!
> 
w00t! :)
> Personally I like all these changes except for the introduction of a couple of ellipsis characters - just because I worry that non-ASCII characters in a README might fail to render correctly in some contexts because there's no explicitly specified encoding. Am I being foolishly conservative?
> 
You'll find no shortage of people who are pro-, neutral-, and against-Unicode in contexts like this. Personally, my take is that it's 2015, so let's everybody embrace Unicode already! 

But it would be inaccurate to call it “foolishly conservative” when you'll find people who hold the mirror opinion as well. I suppose that, at the end of the day, it's still just a matter of preference. 

> Plus, I'd like to add a "Thanks" line for Zearin (for anyone who contributes, obviously, apologies to anyone that has been accidentally missed)
> 
That's fine with me. (And my thanks!)

Let me know if you change your mind about the Unicode, and I'll update the pull request.

**Comment by wiggin15** [comment]
I have to agree with @tartley about the ellipsis. 2015 or not, we don't yet put unicode characters in code,  and some terminals don't like unicode characters (e.g. 'cat README.rst' or 'git show' won't show this character on Windows cmd).

**Comment by Zearin** [comment]
> I have to agree with @tartley about the ellipsis. 2015 or not, we don't yet put unicode characters in code

“We”?  Whom are you speaking for?

**Comment by Zearin** [comment]
Unicode characters removed. :)

**Comment by Zearin** [comment]
D'oh!  The second commit screwed up some formatting under “Thanks”.  Now fixed (along with a few other minor tweaks).

**Comment by wiggin15** [comment]
I suppose I was referring to programmers as a whole ;)

**Pull request merged**
