### PR TITLE
Fixed bug with Fore.RESET after any LIGHT_EX for Issue #57

### PR DESCRIPTION
**Pull request by andyneff**
Returned the "light" brightness to normal for non-light colors

### CODE REVIEW

**Comment by wiggin15** [comment]
Consider this code:

    print colorama.Fore.RED + colorama.Style.BRIGHT + "this should be bright" + colorama.Fore.RESET
    print colorama.Fore.RED + "this should still be bright" + colorama.Fore.RESET

In this case the second print should also be light (the style was not reset), but with your commit it will auto-reset.

Perhaps a different approach would be to remember `self._style` in `fore` and `back` before changing it and re-assigning it after the call to `set_console`. What do you think?

**Comment by andyneff** [comment]
@wiggin15 Yes to second one should be BRIGHT_BACKGROUND
@wiggin15 Are you suggesting adding another attribute for Windows to handle light? Upon reflection of how it does work in Linux, this makes a lot of sense (I think this is what tartley/colorama#20 was talking about towards the end)

```python
import colorama

colorama.init()

print colorama.Style.BRIGHT+'normal' + colorama.Fore.RED + 'red' \
      + colorama.Fore.RESET + 'normal' + colorama.Fore.LIGHTRED_EX \
      + 'light red' + colorama.Fore.RESET +'normal' + colorama.Style.NORMAL
print 'normal' + colorama.Fore.RED + 'red' + colorama.Fore.RESET + 'normal' \
      + colorama.Fore.LIGHTRED_EX + 'light red' + colorama.Fore.RESET +'normal'
print colorama.Style.BRIGHT+'normal' + colorama.Back.RED + 'red' \
      + colorama.Back.RESET + 'normal' + colorama.Back.LIGHTRED_EX \
      + 'light red' + colorama.Back.RESET +'normal' + colorama.Style.NORMAL
print 'normal' + colorama.Back.RED + 'red' + colorama.Back.RESET + 'normal' \
      + colorama.Back.LIGHTRED_EX + 'light red' + colorama.Back.RESET +'normal'

print colorama.Fore.RED + colorama.Style.BRIGHT + "this should be bright" \
      + colorama.Fore.RESET
print colorama.Fore.RED + colorama.Style.BRIGHT + "this should be bright" \
      + colorama.Fore.RESET
print colorama.Fore.RED + "this should still be bright" + colorama.Fore.RESET
print colorama.Fore.RED + "this should still be bright" + colorama.Fore.RESET

```
Now produces the desirable results?
windows2

andyneff/colorama@301523fe76201c1450f97ef6098b6f17d8b054fd

**Comment by wiggin15** [comment]
I came up with something a little simpler: https://github.com/wiggin15/colorama/commit/28d6f63468e0dcfd6b431b3a78bf617f08d1dcd0 .
Can you please check the branch at: https://github.com/wiggin15/colorama
and let me know if that works correctly on all the cases above? Thanks.

**Comment by andyneff** [comment]
Works perfectly!

Thanks

**Comment by andyneff** [comment]
Well, that does work perfectly for the test lines I wrote... HOWEVER...

Adding this to the existing tests
```python
print colorama.Style.NORMAL

print 'normal' + colorama.Fore.LIGHTRED_EX + "light red" + colorama.Style.NORMAL\
      + "what am I" + colorama.Fore.RESET
```
In Linux tartley/colorama@5ab7cdd96b72d5bdb0fb25fdb5ac6ddc8cd7bb1f I get
linux2

But in Windows wiggin15/colorama@28d6f63468e0dcfd6b431b3a78bf617f08d1dcd0
windows3

And in Windows andyneff/colorama@301523fe76201c1450f97ef6098b6f17d8b054fd
windows4

Now, I would argue the behavior in Linux makes sense, because in my head, I'm treating "BRIGHT" and "LIGHT" as separable attributes (that just happen to be the same in Windows due to... well Windows, you know)

**Comment by wiggin15** [comment]
The problem here is that the *LIGHT_EX colors change the style, but Back/Fore.RESET only reset the color and not the style.
We need Back/Fore.RESET to reset the style, but only if the style was changed due to the LIGHT_EX colors.

I have to agree that a separate member ('self._light' in this PR) is needed, because there is no
other way to remember if the style was changed due to Style.* or due to *LIGHT_EX.

**Comment by andyneff** [comment]
I believe I agree. So will 301523fe76201c1450f97ef6098b6f17d8b054fd do the trick, or is something still missing?

**Comment by wiggin15** [comment]
Can you just add a comment please explaining what self._light is? (that it is complementary to _style and is used for the LIGHT_EX colors, and we have to use it to separate the RESETs).

**Comment by wiggin15** [comment]
Great. I'll merge this soon. Thanks.

**Pull request merged**
